# Generated by Django 4.0.4 on 2022-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mail',
            field=models.EmailField(blank=b'I01\n', max_length=100),
        ),
    ]
