# Generated by Django 4.0.4 on 2022-05-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_account_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password2',
        ),
    ]
