# Generated by Django 4.0.4 on 2022-05-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_account_password1_remove_account_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
