# Generated by Django 4.0.4 on 2022-05-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_solofftournament_delete_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pass5',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
