# Generated by Django 4.0.4 on 2022-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_account_pass1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='pass1',
        ),
        migrations.AlterField(
            model_name='account',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
