# Generated by Django 4.0.4 on 2022-05-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_remove_account_pass1_alter_account_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='mail',
        ),
    ]
