# Generated by Django 4.0.4 on 2022-05-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_remove_account_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
