# Generated by Django 4.0.4 on 2022-05-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_alter_account_mail_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mail',
            field=models.EmailField(error_messages={'require': 'your mail has been registered with us please go to login page!'}, max_length=254, unique=True),
        ),
    ]
