# Generated by Django 4.0.4 on 2022-05-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_alter_account_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
