# Generated by Django 4.0.4 on 2022-05-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
