# Generated by Django 4.0.4 on 2022-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('mail', models.EmailField(error_messages={'require': 'your mail has been #registered with us please go to login page!'}, max_length=254, unique=True)),
                ('pass5', models.CharField(max_length=30)),
            ],
        ),
    ]
