# Generated by Django 4.0.4 on 2022-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
