# Generated by Django 4.0.4 on 2022-06-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_freefiredata_delete_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freefiredata',
            name='freefireid',
            field=models.IntegerField(),
        ),
    ]
