# Generated by Django 4.0.4 on 2022-06-16 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0032_remove_freefiredata_user_freefiredata_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freefiredata',
            name='id',
        ),
        migrations.AddField(
            model_name='freefiredata',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
