# Generated by Django 4.0.4 on 2022-06-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0036_remove_freefiredata_user_freefiredata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='coddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codname', models.CharField(max_length=30)),
                ('codid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pubgdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubgname', models.CharField(max_length=30)),
                ('pubgid', models.CharField(max_length=30)),
            ],
        ),
    ]
