# Generated by Django 4.0.4 on 2022-06-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0037_coddata_pubgdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubgdata',
            old_name='pubgname',
            new_name='pubggname',
        ),
    ]
