# Generated by Django 4.0.4 on 2022-06-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0039_rename_pubggname_pubgdata_pubgname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pubgdata',
            new_name='pubggdata',
        ),
    ]
