# Generated by Django 4.0.4 on 2022-07-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0055_alter_freefiredata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='freefiredata',
            name='form_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
