# Generated by Django 4.0.4 on 2022-07-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0056_freefiredata_form_submitted'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='freefiredata',
            table='users',
        ),
    ]
