# Generated by Django 4.0.4 on 2022-07-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0057_alter_freefiredata_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freefiredata',
            name='form_submitted',
        ),
        migrations.AlterModelTable(
            name='freefiredata',
            table=None,
        ),
    ]
